 
name: build check workflow

on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install npm
        run: npm install

      # # Runs a set of commands using the runners shell
      # - name: Run tests
      #   run: npm test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ACCESSKEY }}
          aws-secret-access-key: ${{ secrets.SECRETKEY }}
          aws-region: us-east-1



      - name: Zip Artifact
        run: | 
          echo "current build number is ${{github.run_number}}"
          pwd
          ls -al
          echo "present dir is"
          mkdir codedeploy_webapp
            cd codedeploy_webapp
            pwd
            cp ../*.yml .
            cp ../*.json .
            cp ../*md .
            cp ../.gitignore .
            cp ../*.sh .
            mkdir nodejs-webapp
            cd nodejs-webapp
            pwd
            cp -r ../../nodejs-webapp/* .
            ls
            pwd
            cd ..
            zip -r ../webapp-${{github.run_number}}.zip *
            ls
            
   
      - name: Upload Artifact to S3
        run: |
            pwd
            ls -al
            aws configure list
            aws s3 cp webapp-${{github.run_number}}.zip s3://${{secrets.CODE_DEPLOY_S3_BUCKET}} --sse
      - name: Make CodeDeploy API call
        run: |
            echo "Calling CodeDeploy Agent to pick the artifact and deploy on EC2 instance"
            aws deploy create-deployment --application-name "csye6225-webapp" --deployment-group-name "csye6225-webapp-deployment" --s3-location bucket=${{secrets.CODE_DEPLOY_S3_BUCKET}},bundleType=zip,key=webapp-${{github.run_number}}.zip --file-exists-behavior OVERWRITE
            